name: Daily Update qqwry

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 12 * * *'
    
env:
  innoextract_version: 1.9
  arch: amd64
 
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up python
        id: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install requests
          pip install bs4
      
      - name: Get download link from WeChat tweet
        run: |
          link=$(python qqwry.py)
          if [ -z "$link" ]; then
            echo "No link found, exiting"
            exit 0
          fi
            echo ${link}
            echo "LINK=${link}" >> $GITHUB_ENV
      
      - name: Use link to download newest Zip with retry
        run: |
          link=${{ env.LINK }}
          mkdir -p Downloads
          cd Downloads
          retries=0
          max_retries=3
          while [ $retries -lt $max_retries ]; do
            wget --no-check-certificate --user-agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36" $link
            if [ $? -eq 0 ]; then
              break
            fi
            retries=$((retries+1))
            sleep 10
          done
      
      - name: Download innoextract
        if: steps.cache-innoextract.outputs.cache-hit != 'true'
        run: |
          wget https://github.com/dscharrer/innoextract/releases/download/${{ env.innoextract_version }}/innoextract-${{ env.innoextract_version }}-linux.tar.xz
          tar -xvf innoextract-${{ env.innoextract_version }}-linux.tar.xz innoextract-${{ env.innoextract_version }}-linux/bin/${{ env.arch }}/innoextract --strip-components 3

      - name: Get qqwry.dat
        id: dat_date
        shell: pwsh
        run: |
          $zip = (Get-ChildItem Downloads\*.zip)[0].FullName
          $filename = (Get-ChildItem Downloads\*.zip)[0].Name
          $name = $filename.Substring($filename.IndexOf('-') + 1 , $filename.length - $filename.IndexOf('-') - 5)
          echo "dat_date=$name" | Out-File -FilePath $env:GITHUB_ENV
          7z e -y $zip setup.exe
          ./innoextract setup.exe -I qqwry.dat

      - name: Delete Other File
        run: |
          rm -rf innoextract*
          rm -rf setup.exe
          rm -rf app
          rm -rf Downloads
      - name: Commit qqwry.dat
        run: |
          echo $(date +'%Y%m%d') > date.txt
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          if ! git status -s | grep qqwry.dat --quiet; then
            git add .
            git commit -am "$(date +'%Y%m%d')"
            git push -v --progress
          fi
