name: Daily Update qqwry

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 12 * * *'
    
env:
  innoextract_version: 1.9
  arch: amd64
 
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up python
        id: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install requests
          pip install bs4
      
      - name: Get download link from WeChat
        run: |
          python qqwry.py

      - name: Get qqwry.dat
        shell: pwsh
        run: |
          unzip *.zip setup.exe
          ./innoextract setup.exe -I qqwry.dat
          mv app/qqwry.dat qqwry/qqwry.dat

      - name: Delete Other File
        run: |
          rm -rf setup.exe
          rm -rf *.zip
          rm -rf qqwry.dat
          rm -rf app/
          rm -rf Downloads/
      - name: Commit qqwry.dat
        run: |
          echo $(date +'%Y%m%d') > date.txt
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -am "$(date +'%Y%m%d')"
          git push -v --progress
